export type Scholarship = {
  id: string;
  slug: string;
  name: string;
  university: string;
  universityLogo: string;
  country: string;
  countryEmoji: string;
  level: string;
  deadline: string;
  amount: string;
  currency: string;
  category: string;
  tags: string[];
  status: "Open" | "Closing Soon" | "Closed";
  summary: string;
  description: string[];
  coverage: string[];
  eligibilityCriteria: string[];
  requiredLanguage: string;
  eligibleCountries: string;
  applicationProcess: string[];
  summary_table: {
    levelOfStudy: string;
    jurisdiction: string;
    coursesOffered: string;
    amount: string;
    deadline: string;
    programPeriod: string;
  };
  image: string;
  isSaved?: boolean;
};

export const SCHOLARSHIPS: Scholarship[] = [
  {
    id: "american-university-emerging-global-leader",
    slug: "american-university-emerging-global-leader",
    name: "American University Emerging Global Leader Scholarship",
    university: "University of Toronto",
    universityLogo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/University_of_Toronto_coat_of_arms.svg/200px-University_of_Toronto_coat_of_arms.svg.png",
    country: "USA",
    countryEmoji: "🇺🇸",
    level: "Undergraduate, Masters, PhD",
    deadline: "August 2025",
    amount: "$10,000",
    currency: "USD",
    category: "Merit-Based",
    tags: ["Scholarship", "USA", "Leadership", "Undergraduate"],
    status: "Open",
    summary: "Pursue your studies in Canada. Good news! University of Waterloo Scholarships are currently open. In this article we will explain in detail about this scholarship, its benefits and step by step application process. University of Waterloo Scholarship 2024-2025 is a fully funded scholarship for international students. This scholarship is offered for Undergraduate, Masters and PhD studies. Waterloo University scholarship is valued up to $10,000.",
    description: [
      "The American University Emerging Global Leader Scholarship (EGL) is a competitive scholarship for students from developing countries who demonstrate exceptional academic achievement, leadership potential, and a commitment to positive change in their home communities.",
      "This fully-funded scholarship covers tuition, fees, room and board, and provides an annual stipend for books and personal expenses. Recipients also receive access to American University's global network and internship opportunities in Washington D.C.",
    ],
    coverage: [
      "Full tuition fees for the entire degree program",
      "University housing (on-campus accommodation)",
      "Meal plan for the academic year",
      "Annual books and personal expense stipend of $2,500",
      "One-time round-trip airfare from home country",
      "Health insurance coverage during the program",
    ],
    eligibilityCriteria: [
      "Citizens of a developing country (as classified by the World Bank)",
      "Must be applying for a first undergraduate degree — no prior bachelor's degrees",
      "Minimum GPA of 3.8/4.0 or equivalent from home country secondary school",
      "Demonstrated commitment to making a positive impact in their home country",
      "Not a U.S. citizen, U.S. permanent resident, or lawful resident alien",
      "Strong English proficiency — TOEFL 100+, IELTS 7.0+, or equivalent",
      "Financial need — must demonstrate inability to fund study without scholarship",
    ],
    requiredLanguage: "English (IELTS 7.0+ / TOEFL 100+)",
    eligibleCountries: "All developing countries (World Bank classification) including Nepal",
    applicationProcess: [
      "Complete the Common Application (Common App) for undergraduate admission",
      "Submit EGL Scholarship Application via American University portal",
      "Upload official transcripts (translated to English and certified)",
      "Submit 2 letters of recommendation from teachers/counselors",
      "Write a 500-word personal statement on your leadership vision",
      "Provide proof of financial need documentation",
      "TOEFL/IELTS score report (within the last 2 years)",
    ],
    summary_table: {
      levelOfStudy: "Undergraduate (Bachelor's)",
      jurisdiction: "University of Toronto",
      coursesOffered: "All undergraduate programs offered at AU",
      amount: "$10,000 (Annually)",
      deadline: "August 2025",
      programPeriod: "4 Years (Bachelor's degree)",
    },
    image: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "chevening-scholarship-uk",
    slug: "chevening-scholarship-uk",
    name: "Chevening Scholarship 2024-25",
    university: "University of Oxford",
    universityLogo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Oxford-Coat-Of-Arms-Quartrefoil.svg/200px-Oxford-Coat-Of-Arms-Quartrefoil.svg.png",
    country: "UK",
    countryEmoji: "🇬🇧",
    level: "Masters",
    deadline: "November 2025",
    amount: "Full Funding",
    currency: "GBP",
    category: "Government",
    tags: ["Scholarship", "UK", "Leadership", "Masters"],
    status: "Open",
    summary: "Chevening is the UK government's international awards programme, awarded to outstanding emerging leaders from around the world. The scholarship programme makes up a central part of the UK government's foreign policy agenda and is funded by the Foreign, Commonwealth and Development Office (FCDO) and partner organisations.",
    description: [
      "Chevening Scholarships are awarded to exceptional individuals who have demonstrated academic excellence and leadership potential. The programme offers financial support to study at any UK university.",
      "As a Chevening Scholar, you will be part of a prestigious global network of over 50,000 alumni including current and former heads of state, government ministers, scientists, and global influencers.",
    ],
    coverage: [
      "Full university tuition fees",
      "Monthly living allowance (stipend)",
      "Economy class return airfare from your home country",
      "Arrival allowance and departure allowance",
      "Pre-course English language training (if required)",
      "Thesis grant (if applicable)",
    ],
    eligibilityCriteria: [
      "Be a citizen of a Chevening-eligible country (Nepal included)",
      "Return to your home country for a minimum of two years after your scholarship",
      "Have an undergraduate degree that will enable you to gain entry to a UK postgraduate programme",
      "Have at least two years' work experience (2,800 hours)",
      "Apply to three different UK universities and receive an offer from at least one",
      "Meet the English language requirements of your chosen university",
      "Not hold British or dual British citizenship",
    ],
    requiredLanguage: "English (IELTS 6.5+ / TOEFL 89+)",
    eligibleCountries: "Nepal and 160+ countries worldwide",
    applicationProcess: [
      "Submit online application at chevening.org between August and November",
      "Choose and apply to 3 UK universities independently",
      "Complete 4 core essays: career plan, leadership, networking, studying in UK",
      "Shortlisting by the British Embassy in your home country",
      "Interview at the British Embassy/High Commission",
      "Receive conditional offer from at least one chosen university",
      "Final confirmation and scholarship award",
    ],
    summary_table: {
      levelOfStudy: "Masters (1-year)",
      jurisdiction: "University of Oxford, Cambridge & all UK universities",
      coursesOffered: "All subject areas",
      amount: "Full Funding (tuition + living + flights)",
      deadline: "November 2025",
      programPeriod: "1 year (Masters)",
    },
    image: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "australia-awards-scholarship",
    slug: "australia-awards-scholarship",
    name: "Australia Awards Scholarships 2024",
    university: "University of Melbourne",
    universityLogo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/University_of_Melbourne_logo.svg/200px-University_of_Melbourne_logo.svg.png",
    country: "Australia",
    countryEmoji: "🇦🇺",
    level: "Masters, PhD",
    deadline: "April 2025",
    amount: "Full Funding",
    currency: "AUD",
    category: "Government",
    tags: ["Scholarship", "Australia", "Government", "PhD"],
    status: "Closing Soon",
    summary: "Australia Awards are long-term awards that aim to develop the skills and human resource capacity of partner countries to promote their economic growth and stability. Scholarships are offered to international students for full-time undergraduate and postgraduate studies at participating Australian universities.",
    description: [
      "Australia Awards Scholarships (AAS) are the flagship Australian Government program offering long-term development scholarships. The scholarships provide opportunities to undertake full-time undergraduate or postgraduate study at participating Australian universities.",
      "Recipients study alongside Australian students, gaining knowledge and skills applicable to their country's development priorities. Australia Awards Scholarships are fully funded and support students for the entire duration of their program.",
    ],
    coverage: [
      "Full tuition fees for the duration of the course",
      "Return economy class airfares",
      "Establishment allowance (paid on arrival)",
      "Contribution to Living Expenses (CLE) — approximately AUD 3,000/month",
      "Introductory Academic Program before course commencement",
      "Overseas Student Health Cover (OSHC) for the duration of the award",
      "Academic support supplements if required",
    ],
    eligibilityCriteria: [
      "Citizen of an Australia Awards-eligible country (Nepal is eligible)",
      "Not currently in Australia and not have a spouse/de-facto partner who is an Australian citizen",
      "Meet the minimum academic requirements — typically GPA 3.0+ for Masters",
      "Not have previously received an Australia Awards Scholarship",
      "Demonstrate a commitment to your country's development and intention to return",
    ],
    requiredLanguage: "English (IELTS 6.5 overall / PTE 58)",
    eligibleCountries: "Nepal and all Australia Awards eligible countries",
    applicationProcess: [
      "Apply through the Australia Awards online application portal (oasis.dfat.gov.au)",
      "Choose up to 3 Australian universities and programs",
      "Submit personal statement, CV, and academic transcripts",
      "Provide 2 professional references",
      "Shortlisted candidates may be invited for an interview",
      "Apply to your chosen university for admission (separately)",
      "Medical examination required for successful candidates",
    ],
    summary_table: {
      levelOfStudy: "Masters, PhD",
      jurisdiction: "Multiple Australian Universities",
      coursesOffered: "All fields aligned with development priorities",
      amount: "Full Funding (tuition + living + flights)",
      deadline: "April 2025",
      programPeriod: "1–4 years",
    },
    image: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "canada-vanier-graduate-scholarship",
    slug: "canada-vanier-graduate-scholarship",
    name: "Vanier Canada Graduate Scholarship",
    university: "University of British Columbia",
    universityLogo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/University_of_British_Columbia_coat_of_arms.svg/200px-University_of_British_Columbia_coat_of_arms.svg.png",
    country: "Canada",
    countryEmoji: "🇨🇦",
    level: "PhD",
    deadline: "October 2025",
    amount: "CAD 50,000",
    currency: "CAD",
    category: "Merit-Based",
    tags: ["Scholarship", "Canada", "PhD", "Research"],
    status: "Open",
    summary: "The Vanier Canada Graduate Scholarships (Vanier CGS) program is designed to attract and retain world-class doctoral students by supporting students who demonstrate both leadership skills and a high standard of scholarly achievement in graduate studies in the social sciences and/or humanities, natural sciences and/or engineering, and health.",
    description: [
      "The Vanier Canada Graduate Scholarships (Vanier CGS) program is designed to attract and retain world-class doctoral students by supporting students who demonstrate both leadership skills and a high standard of scholarly achievement.",
      "Valued at $50,000 per year for three years, the Vanier CGS is one of the most prestigious doctoral fellowships in Canada and is open to both Canadian citizens and international students.",
    ],
    coverage: [
      "CAD $50,000 per year for 3 years (total CAD $150,000)",
      "Research stipend included",
      "Conference travel funding (through host institution)",
      "No restrictions on the use of funding outside of research-related activities",
    ],
    eligibilityCriteria: [
      "Nominated by a Canadian university — cannot apply directly",
      "Must be pursuing a doctoral degree (PhD) at a Canadian institution",
      "Have completed no more than 20 months of doctoral studies at the time of nomination",
      "Demonstrate leadership skills in academic and community contexts",
      "Achieve high academic performance (minimum average A-)",
      "Conduct research in health, natural sciences, engineering, social sciences or humanities",
    ],
    requiredLanguage: "English or French (institutional requirement)",
    eligibleCountries: "Open to all nationalities including Nepal",
    applicationProcess: [
      "Contact your intended Canadian university research supervisor to discuss nomination",
      "Be nominated by your Canadian university — each university has limited nomination spots",
      "Prepare research proposal, CV, and leadership portfolio",
      "Submit references from 3 academic/professional referees",
      "University submits nomination package to Vanier-Banting Secretariat",
      "Results announced in April each year",
    ],
    summary_table: {
      levelOfStudy: "PhD (Doctoral)",
      jurisdiction: "University of British Columbia & all Canadian universities",
      coursesOffered: "Health, Natural Sciences, Engineering, Social Sciences, Humanities",
      amount: "CAD $50,000/year for 3 years",
      deadline: "October 2025",
      programPeriod: "3 years (PhD program)",
    },
    image: "https://images.unsplash.com/photo-1517935706615-2717063c2225?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "new-zealand-commonwealth-scholarship",
    slug: "new-zealand-commonwealth-scholarship",
    name: "New Zealand Commonwealth Scholarship",
    university: "University of Auckland",
    universityLogo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/University_of_Melbourne_logo.svg/200px-University_of_Melbourne_logo.svg.png",
    country: "New Zealand",
    countryEmoji: "🇳🇿",
    level: "Masters, PhD",
    deadline: "March 2025",
    amount: "Full Funding",
    currency: "NZD",
    category: "Government",
    tags: ["Scholarship", "New Zealand", "Commonwealth", "Masters"],
    status: "Closing Soon",
    summary: "New Zealand Commonwealth Scholarships provide opportunities for people from eligible Commonwealth countries to study in New Zealand, helping to develop their countries through sustainable growth, reducing inequality, and supporting good governance.",
    description: [
      "The New Zealand Commonwealth Scholarships offer full funding for students from Commonwealth developing countries to pursue postgraduate studies in New Zealand.",
      "The scholarship is tied to development outcomes and recipients are expected to return to their home countries and apply their knowledge for the benefit of their communities.",
    ],
    coverage: [
      "Full university tuition fees",
      "Return economy airfares",
      "NZD $22,000 annual living allowance",
      "Accommodation support",
      "Health insurance coverage",
      "Settling-in allowance on arrival",
    ],
    eligibilityCriteria: [
      "Be a citizen of a Commonwealth country (Nepal is a member of the Commonwealth)",
      "Be currently resident in a Commonwealth developing country",
      "Have a Bachelor's degree with high academic standing",
      "Not hold New Zealand citizenship or permanent residency",
      "Demonstrate clear development impact goals",
    ],
    requiredLanguage: "English (IELTS 6.5+)",
    eligibleCountries: "All Commonwealth developing countries including Nepal",
    applicationProcess: [
      "Submit application through the NZ Commonwealth Scholarship portal",
      "Obtain a conditional offer from a New Zealand university (required before applying)",
      "Submit academic transcripts, CV, and 3 professional references",
      "Write a development impact statement (how studies will benefit your home country)",
      "Medical and police clearance (for shortlisted candidates)",
    ],
    summary_table: {
      levelOfStudy: "Masters, PhD",
      jurisdiction: "All New Zealand Universities",
      coursesOffered: "Development-related fields prioritized",
      amount: "Full Funding",
      deadline: "March 2025",
      programPeriod: "1–3 years",
    },
    image: "https://images.unsplash.com/photo-1507699622108-4be3abd695ad?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "ireland-government-scholarship",
    slug: "ireland-government-scholarship",
    name: "Ireland Govt. International Education Scholarship",
    university: "Trinity College Dublin",
    universityLogo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Oxford-Coat-Of-Arms-Quartrefoil.svg/200px-Oxford-Coat-Of-Arms-Quartrefoil.svg.png",
    country: "Ireland",
    countryEmoji: "🇮🇪",
    level: "Undergraduate, Masters",
    deadline: "May 2025",
    amount: "€10,000",
    currency: "EUR",
    category: "Government",
    tags: ["Scholarship", "Ireland", "Government", "Europe"],
    status: "Open",
    summary: "The Government of Ireland International Education Scholarships (GOI-IES) are prestigious awards that offer fully funded fee waivers and a living stipend for international students to pursue undergraduate or postgraduate study in Ireland.",
    description: [
      "The Government of Ireland International Education Scholarships offer world-class education in one of Europe's most dynamic knowledge economies.",
      "Recipients become ambassadors for Ireland and are expected to promote Ireland as a study destination upon returning to their home countries.",
    ],
    coverage: [
      "€10,000 fee contribution per year",
      "Waiver of international tuition fees up to the scholarship limit",
      "Living allowance for the duration of studies",
    ],
    eligibilityCriteria: [
      "Not be a citizen of Ireland, the UK, or the EU/EEA",
      "Have an excellent academic record (top 5% of your class)",
      "Apply to an eligible Irish higher education institution",
      "Be applying for full-time study",
    ],
    requiredLanguage: "English (IELTS 6.0+)",
    eligibleCountries: "Nepal and all non-EU/EEA countries",
    applicationProcess: [
      "Apply to an Irish higher education institution and obtain a conditional offer",
      "Apply for the scholarship through IrishScholarships.ie portal",
      "Submit personal statement and academic transcripts",
      "Interview (for shortlisted candidates)",
    ],
    summary_table: {
      levelOfStudy: "Undergraduate, Masters",
      jurisdiction: "All Irish Higher Education Institutions",
      coursesOffered: "All approved programs",
      amount: "€10,000/year",
      deadline: "May 2025",
      programPeriod: "1–4 years",
    },
    image: "https://images.unsplash.com/photo-1564959130747-897fb406b9af?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "daad-scholarship-germany",
    slug: "daad-scholarship-germany",
    name: "DAAD Scholarship — Study in Germany",
    university: "Technical University of Munich",
    universityLogo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/University_of_Melbourne_logo.svg/200px-University_of_Melbourne_logo.svg.png",
    country: "Europe",
    countryEmoji: "🇩🇪",
    level: "Masters, PhD",
    deadline: "October 2025",
    amount: "€934/month",
    currency: "EUR",
    category: "Research",
    tags: ["Scholarship", "Germany", "Research", "STEM"],
    status: "Open",
    summary: "DAAD (German Academic Exchange Service) scholarships support international students and researchers for study and research stays in Germany, promoting international academic exchange.",
    description: [
      "The DAAD Scholarship is one of the world's largest funding organizations for international exchange of students and researchers. With over 100,000 grants awarded annually, DAAD scholarships make German higher education accessible to international students.",
      "Germany charges no tuition fees at public universities — the DAAD scholarship covers your living expenses, making top German university education essentially free.",
    ],
    coverage: [
      "Monthly stipend of €934 (Masters) or €1,200 (PhD)",
      "Health, accident, and liability insurance",
      "Travel allowance (one-time)",
      "Study and research allowance",
      "Rent subsidy (if applicable based on income)",
    ],
    eligibilityCriteria: [
      "Hold a very good first degree (bachelor's or equivalent)",
      "Have completed your first degree no earlier than 6 years before the application deadline",
      "Demonstrate strong academic record (good to excellent grades)",
      "Have relevant work experience (for some scholarship categories)",
    ],
    requiredLanguage: "German (B2 for German-taught programs) or English (C1 for English programs)",
    eligibleCountries: "All countries including Nepal",
    applicationProcess: [
      "Identify the appropriate DAAD scholarship program for your profile",
      "Apply to a German university and obtain admission",
      "Submit online application via DAAD portal (funding-guide.daad.de)",
      "Provide German language certificate (if applicable) and academic transcripts",
      "Complete motivation letter and research proposal",
    ],
    summary_table: {
      levelOfStudy: "Masters, PhD, Research",
      jurisdiction: "All German Public Universities",
      coursesOffered: "Engineering, Natural Sciences, STEM (and more)",
      amount: "€934–€1,200/month + allowances",
      deadline: "October 2025",
      programPeriod: "1–3 years",
    },
    image: "https://images.unsplash.com/photo-1559570278-eb3e76f5e3d1?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "fulbright-foreign-student-program",
    slug: "fulbright-foreign-student-program",
    name: "Fulbright Foreign Student Program 2025",
    university: "Harvard University",
    universityLogo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/University_of_British_Columbia_coat_of_arms.svg/200px-University_of_British_Columbia_coat_of_arms.svg.png",
    country: "USA",
    countryEmoji: "🇺🇸",
    level: "Masters, PhD",
    deadline: "September 2025",
    amount: "Full Funding",
    currency: "USD",
    category: "Government",
    tags: ["Scholarship", "USA", "Fulbright", "Research"],
    status: "Open",
    summary: "The Fulbright Foreign Student Program enables graduate students, young professionals, and artists from abroad to research and study in the United States for one year or longer. The program operates in more than 160 countries worldwide.",
    description: [
      "The Fulbright Program is the U.S. government's flagship international educational exchange program. Since its establishment in 1946, the Fulbright Program has provided approximately 390,000 participants with the opportunity to observe each other's political, economic, educational, and cultural institutions.",
      "Fulbright Nepal is administered by the United States Educational Foundation in Nepal (USEF/Fulbright Nepal) in Kathmandu.",
    ],
    coverage: [
      "Full university tuition and fees",
      "Monthly living stipend",
      "Round-trip airfare between Nepal and the USA",
      "Health insurance",
      "Book and equipment allowance",
      "Enrichment activities and program events",
    ],
    eligibilityCriteria: [
      "Nepali citizen currently residing in Nepal",
      "Fluent in English",
      "Hold a Bachelor's degree with at least a 3.5 GPA (or equivalent)",
      "Demonstrate leadership potential and commitment to return to Nepal",
      "Apply in your home country through the local Fulbright Commission (USEF Nepal)",
    ],
    requiredLanguage: "English (TOEFL 79+ / IELTS 6.5+)",
    eligibleCountries: "Nepal (administered through USEF Nepal, Kathmandu)",
    applicationProcess: [
      "Application opens in May — check usef.org.np for exact dates",
      "Submit online application via IIE online application system",
      "Complete essays: personal statement, study objectives, personal/professional background",
      "Submit official transcripts (translated and certified)",
      "3 recommendation letters from academic/professional references",
      "Attend interview at USEF Nepal office in Kathmandu",
      "Selected finalists forwarded to US for final review",
    ],
    summary_table: {
      levelOfStudy: "Masters, PhD",
      jurisdiction: "Harvard, MIT, Stanford & all US universities",
      coursesOffered: "All fields aligned with development goals",
      amount: "Full Funding",
      deadline: "September 2025",
      programPeriod: "1–3 years",
    },
    image: "https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "mastercard-foundation-scholars",
    slug: "mastercard-foundation-scholars",
    name: "Mastercard Foundation Scholars Program",
    university: "University of Edinburgh",
    universityLogo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Oxford-Coat-Of-Arms-Quartrefoil.svg/200px-Oxford-Coat-Of-Arms-Quartrefoil.svg.png",
    country: "UK",
    countryEmoji: "🇬🇧",
    level: "Undergraduate, Masters",
    deadline: "January 2026",
    amount: "Full Funding",
    currency: "USD",
    category: "Merit-Based",
    tags: ["Scholarship", "UK", "Leadership", "Africa", "Global"],
    status: "Open",
    summary: "The Mastercard Foundation Scholars Program provides transformative scholarships for young people from Africa and other developing regions to study at world-class universities. Scholars receive academic, financial, and social support to become leaders who give back to their communities.",
    description: [
      "The Mastercard Foundation Scholars Program enables academically talented but financially disadvantaged young people to access higher education at leading universities around the world.",
    ],
    coverage: [
      "Full tuition fees",
      "Living expenses and accommodation",
      "Round-trip airfare",
      "Health insurance",
      "Leadership development programming and mentorship",
    ],
    eligibilityCriteria: [
      "Demonstrate academic excellence and leadership potential",
      "Come from a financially disadvantaged background",
      "Commitment to giving back to communities in need",
    ],
    requiredLanguage: "English (IELTS 7.0+)",
    eligibleCountries: "Sub-Saharan Africa focus, some programs open globally",
    applicationProcess: [
      "Apply to participating universities directly",
      "The university nominates candidates for the scholarship",
      "Complete Mastercard Foundation Scholars Program application within the university portal",
    ],
    summary_table: {
      levelOfStudy: "Undergraduate, Masters",
      jurisdiction: "University of Edinburgh & partner universities",
      coursesOffered: "All fields",
      amount: "Full Funding",
      deadline: "January 2026",
      programPeriod: "3–4 years",
    },
    image: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=1200&q=80",
  },
];

export const SCHOLARSHIP_FILTER_TAGS = ["All", "Courses", "Visa Processing", "Study in USA", "Study in UK", "Insurance", "Expenses", "Jobs", "Study Abroad", "Work Permit", "Scholarship"];

export const SCHOLARSHIP_COUNTRIES = [
  { name: "Australia", emoji: "🇦🇺" },
  { name: "Canada",    emoji: "🇨🇦" },
  { name: "USA",       emoji: "🇺🇸" },
  { name: "UK",        emoji: "🇬🇧" },
  { name: "New Zealand", emoji: "🇳🇿" },
  { name: "Ireland",   emoji: "🇮🇪" },
  { name: "India",     emoji: "🇮🇳" },
  { name: "Bangladesh", emoji: "🇧🇩" },
  { name: "Dubai",     emoji: "🇦🇪" },
  { name: "Europe",    emoji: "🇪🇺" },
];

export const SCHOLARSHIP_FAQS = [
  {
    q: "What is Unifinders Scholarship?",
    a: "Unifinders Scholarship is our curated database of scholarships available for Nepali students. We list verified, regularly updated scholarship opportunities from universities and governments worldwide and provide guidance on how to apply.",
  },
  {
    q: "Who is eligible for Unifinders Scholarship?",
    a: "Most scholarships on our platform are open to Nepali students and students from other South Asian countries. Each scholarship has its own eligibility criteria including GPA requirements, language test scores, and program type. Our counselors can help you identify the best fit.",
  },
  {
    q: "How can I apply for Unifinders Scholarship?",
    a: "Click 'Apply for Scholarship' on any scholarship page to access the direct application link. You can also book a free counseling session with our scholarship experts who will guide you through the entire application process.",
  },
  {
    q: "What documents are required for scholarship applications?",
    a: "Requirements vary per scholarship but typically include: passport copy, academic transcripts, English language test results (IELTS/TOEFL/PTE), letters of recommendation, personal statement, financial documents, and police clearance certificate.",
  },
  {
    q: "Does Unifinders charge for scholarship assistance?",
    a: "Our scholarship guidance and counseling sessions are free of charge. We are committed to making study abroad accessible to all qualified Nepali students regardless of financial background.",
  },
];
