/**
 * Real university data for seeding — focused on countries
 * where Nepali students commonly study abroad.
 */
export const UNIVERSITIES = [
  // ─── Australia ──────────────────────────────────────────
  {
    name: "University of Melbourne",
    country: "Australia",
    city: "Melbourne",
    type: "Public",
    established: 1853,
    ranking: 14,
    websiteUrl: "https://www.unimelb.edu.au",
    coverImageUrl: "https://images.unsplash.com/photo-1562774053-701939374585?w=800&auto=format&fit=crop",
    description: "The University of Melbourne is a public research university located in Melbourne, Australia. Founded in 1853, it is the second oldest university in Australia and the oldest in Victoria.",
    intakes: ["February", "July"],
    minIelts: 6.5,
    minToefl: 79,
    minGpa: 3.0,
    tuitionRangeMin: 30000,
    tuitionRangeMax: 50000,
    applicationFee: 100,
    studentCount: 53000,
    acceptanceRate: 0.70,
    programs: [
      { name: "Master of Information Technology", level: "Masters", field: "Computer Science", duration: "2 years", tuitionFee: 47636 },
      { name: "Bachelor of Commerce", level: "Bachelors", field: "Business", duration: "3 years", tuitionFee: 44736 },
      { name: "Master of Engineering (Software)", level: "Masters", field: "Engineering", duration: "2-3 years", tuitionFee: 48000 },
      { name: "Master of Data Science", level: "Masters", field: "Computer Science", duration: "2 years", tuitionFee: 47636 },
      { name: "Bachelor of Science", level: "Bachelors", field: "Science", duration: "3 years", tuitionFee: 42784 },
      { name: "Master of Public Health", level: "Masters", field: "Health Sciences", duration: "2 years", tuitionFee: 40000 },
    ],
  },
  {
    name: "Monash University",
    country: "Australia",
    city: "Melbourne",
    type: "Public",
    established: 1958,
    ranking: 42,
    websiteUrl: "https://www.monash.edu",
    coverImageUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&auto=format&fit=crop",
    description: "Monash University is a public research university based in Melbourne, Australia. It is a member of the Group of Eight and the only Australian member of the M8 Alliance.",
    intakes: ["February", "July"],
    minIelts: 6.5,
    minToefl: 79,
    minGpa: 2.8,
    tuitionRangeMin: 28000,
    tuitionRangeMax: 48000,
    applicationFee: 110,
    studentCount: 86000,
    acceptanceRate: 0.55,
    programs: [
      { name: "Master of Information Technology", level: "Masters", field: "Computer Science", duration: "1.5-2 years", tuitionFee: 42800 },
      { name: "Bachelor of Engineering (Honours)", level: "Bachelors", field: "Engineering", duration: "4 years", tuitionFee: 48000 },
      { name: "Master of Business Administration", level: "Masters", field: "Business", duration: "2 years", tuitionFee: 49500 },
      { name: "Bachelor of Nursing", level: "Bachelors", field: "Health Sciences", duration: "3 years", tuitionFee: 38400 },
      { name: "Master of Data Science", level: "Masters", field: "Computer Science", duration: "1.5-2 years", tuitionFee: 42800 },
    ],
  },
  {
    name: "University of Sydney",
    country: "Australia",
    city: "Sydney",
    type: "Public",
    established: 1850,
    ranking: 18,
    websiteUrl: "https://www.sydney.edu.au",
    coverImageUrl: "https://images.unsplash.com/photo-1525926472898-acbfcb5064db?w=800&auto=format&fit=crop",
    description: "The University of Sydney is an Australian public research university in Sydney, Australia. Founded in 1850, it is Australia's first university and is regarded as one of the world's leading universities.",
    intakes: ["February", "July"],
    minIelts: 6.5,
    minToefl: 85,
    minGpa: 3.0,
    tuitionRangeMin: 35000,
    tuitionRangeMax: 52000,
    applicationFee: 150,
    studentCount: 73000,
    acceptanceRate: 0.30,
    programs: [
      { name: "Master of Information Technology", level: "Masters", field: "Computer Science", duration: "1.5 years", tuitionFee: 49000 },
      { name: "Bachelor of Engineering Honours (Software)", level: "Bachelors", field: "Engineering", duration: "4 years", tuitionFee: 52500 },
      { name: "Master of Commerce", level: "Masters", field: "Business", duration: "2 years", tuitionFee: 51000 },
      { name: "Bachelor of Nursing (Advanced Studies)", level: "Bachelors", field: "Health Sciences", duration: "3 years", tuitionFee: 40500 },
    ],
  },
  {
    name: "Deakin University",
    country: "Australia",
    city: "Geelong",
    type: "Public",
    established: 1974,
    ranking: 266,
    websiteUrl: "https://www.deakin.edu.au",
    coverImageUrl: "https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=800&auto=format&fit=crop",
    description: "Deakin University is an Australian public university headquartered in Geelong, Victoria. Known for its innovative teaching and strong industry connections.",
    intakes: ["March", "July", "November"],
    minIelts: 6.0,
    minToefl: 60,
    minGpa: 2.5,
    tuitionRangeMin: 22000,
    tuitionRangeMax: 38000,
    applicationFee: 0,
    studentCount: 64000,
    acceptanceRate: 0.70,
    programs: [
      { name: "Master of Information Technology", level: "Masters", field: "Computer Science", duration: "1.5-2 years", tuitionFee: 35200 },
      { name: "Bachelor of Information Technology", level: "Bachelors", field: "Computer Science", duration: "3 years", tuitionFee: 34600 },
      { name: "Master of Business Administration", level: "Masters", field: "Business", duration: "1.5 years", tuitionFee: 42600 },
      { name: "Bachelor of Nursing", level: "Bachelors", field: "Health Sciences", duration: "3 years", tuitionFee: 34400 },
    ],
  },
  {
    name: "RMIT University",
    country: "Australia",
    city: "Melbourne",
    type: "Public",
    established: 1887,
    ranking: 140,
    websiteUrl: "https://www.rmit.edu.au",
    coverImageUrl: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=800&auto=format&fit=crop",
    description: "RMIT University is an Australian public research university in Melbourne. It is an urban, multi-sector university known for technology, design, and enterprise.",
    intakes: ["February", "July"],
    minIelts: 6.5,
    minToefl: 79,
    minGpa: 2.7,
    tuitionRangeMin: 25000,
    tuitionRangeMax: 42000,
    applicationFee: 0,
    studentCount: 96000,
    acceptanceRate: 0.55,
    programs: [
      { name: "Master of Information Technology", level: "Masters", field: "Computer Science", duration: "2 years", tuitionFee: 36480 },
      { name: "Bachelor of Computer Science", level: "Bachelors", field: "Computer Science", duration: "3 years", tuitionFee: 36480 },
      { name: "Master of Engineering (Management)", level: "Masters", field: "Engineering", duration: "2 years", tuitionFee: 39360 },
    ],
  },
  // ─── Canada ─────────────────────────────────────────────
  {
    name: "University of Toronto",
    country: "Canada",
    city: "Toronto",
    type: "Public",
    established: 1827,
    ranking: 21,
    websiteUrl: "https://www.utoronto.ca",
    coverImageUrl: "https://images.unsplash.com/photo-1569982175971-d92b01cf8694?w=800&auto=format&fit=crop",
    description: "The University of Toronto is a public research university in Toronto, Ontario. It was founded in 1827 and is the leading Canadian institution of learning.",
    intakes: ["September", "January", "May"],
    minIelts: 6.5,
    minToefl: 89,
    minGpa: 3.3,
    tuitionRangeMin: 40000,
    tuitionRangeMax: 58000,
    applicationFee: 180,
    studentCount: 97000,
    acceptanceRate: 0.43,
    programs: [
      { name: "Master of Science in Computer Science", level: "Masters", field: "Computer Science", duration: "1.5 years", tuitionFee: 52230 },
      { name: "Bachelor of Applied Science (Engineering)", level: "Bachelors", field: "Engineering", duration: "4 years", tuitionFee: 58680 },
      { name: "Master of Business Administration", level: "Masters", field: "Business", duration: "2 years", tuitionFee: 56000 },
      { name: "Bachelor of Science", level: "Bachelors", field: "Science", duration: "4 years", tuitionFee: 57020 },
    ],
  },
  {
    name: "University of British Columbia",
    country: "Canada",
    city: "Vancouver",
    type: "Public",
    established: 1908,
    ranking: 34,
    websiteUrl: "https://www.ubc.ca",
    coverImageUrl: "https://images.unsplash.com/photo-1590012314607-cda9d9b699ae?w=800&auto=format&fit=crop",
    description: "The University of British Columbia is a public research university with campuses in Vancouver and Kelowna. It is consistently ranked among the top universities in the world.",
    intakes: ["September", "January"],
    minIelts: 6.5,
    minToefl: 90,
    minGpa: 3.0,
    tuitionRangeMin: 35000,
    tuitionRangeMax: 52000,
    applicationFee: 168,
    studentCount: 72000,
    acceptanceRate: 0.52,
    programs: [
      { name: "Master of Science in Computer Science", level: "Masters", field: "Computer Science", duration: "2 years", tuitionFee: 9131 },
      { name: "Bachelor of Computer Science", level: "Bachelors", field: "Computer Science", duration: "4 years", tuitionFee: 42803 },
      { name: "Master of Management", level: "Masters", field: "Business", duration: "1 year", tuitionFee: 37800 },
      { name: "Bachelor of Engineering", level: "Bachelors", field: "Engineering", duration: "4 years", tuitionFee: 52000 },
    ],
  },
  {
    name: "Conestoga College",
    country: "Canada",
    city: "Kitchener",
    type: "Public",
    established: 1967,
    ranking: null,
    websiteUrl: "https://www.conestogac.on.ca",
    coverImageUrl: "https://images.unsplash.com/photo-1523050854058-8df90110c7f1?w=800&auto=format&fit=crop",
    description: "Conestoga College is a public college of applied arts and technology in Kitchener, Ontario. Popular among international students for its practical, career-oriented programs.",
    intakes: ["September", "January", "May"],
    minIelts: 6.0,
    minToefl: 79,
    minGpa: 2.5,
    tuitionRangeMin: 14000,
    tuitionRangeMax: 22000,
    applicationFee: 100,
    studentCount: 26000,
    acceptanceRate: 0.75,
    programs: [
      { name: "Software Engineering Technology", level: "Diploma", field: "Computer Science", duration: "3 years", tuitionFee: 17234 },
      { name: "Business Administration - Management", level: "Diploma", field: "Business", duration: "3 years", tuitionFee: 15600 },
      { name: "Mechanical Engineering Technology", level: "Diploma", field: "Engineering", duration: "3 years", tuitionFee: 17234 },
      { name: "Practical Nursing", level: "Diploma", field: "Health Sciences", duration: "2 years", tuitionFee: 16800 },
    ],
  },
  // ─── United Kingdom ─────────────────────────────────────
  {
    name: "University College London",
    country: "United Kingdom",
    city: "London",
    type: "Public",
    established: 1826,
    ranking: 9,
    websiteUrl: "https://www.ucl.ac.uk",
    coverImageUrl: "https://images.unsplash.com/photo-1517502166878-35c93a0072f0?w=800&auto=format&fit=crop",
    description: "University College London is a public research university in London, England. It is a member of the Russell Group and part of the University of London federation.",
    intakes: ["September"],
    minIelts: 6.5,
    minToefl: 92,
    minGpa: 3.3,
    tuitionRangeMin: 24000,
    tuitionRangeMax: 38000,
    applicationFee: 0,
    studentCount: 46000,
    acceptanceRate: 0.63,
    programs: [
      { name: "MSc Computer Science", level: "Masters", field: "Computer Science", duration: "1 year", tuitionFee: 36100 },
      { name: "BSc Computer Science", level: "Bachelors", field: "Computer Science", duration: "3 years", tuitionFee: 35000 },
      { name: "MSc Data Science", level: "Masters", field: "Computer Science", duration: "1 year", tuitionFee: 36100 },
      { name: "MSc Management", level: "Masters", field: "Business", duration: "1 year", tuitionFee: 35400 },
    ],
  },
  {
    name: "University of Leeds",
    country: "United Kingdom",
    city: "Leeds",
    type: "Public",
    established: 1904,
    ranking: 75,
    websiteUrl: "https://www.leeds.ac.uk",
    coverImageUrl: "https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=800&auto=format&fit=crop",
    description: "The University of Leeds is one of the largest universities in the UK, with around 38,000 students. It is a member of the Russell Group of research-intensive universities.",
    intakes: ["September", "January"],
    minIelts: 6.0,
    minToefl: 87,
    minGpa: 2.8,
    tuitionRangeMin: 20000,
    tuitionRangeMax: 28000,
    applicationFee: 0,
    studentCount: 38000,
    acceptanceRate: 0.73,
    programs: [
      { name: "MSc Advanced Computer Science", level: "Masters", field: "Computer Science", duration: "1 year", tuitionFee: 28250 },
      { name: "BA Business Management", level: "Bachelors", field: "Business", duration: "3 years", tuitionFee: 24500 },
      { name: "MSc Data Science and Analytics", level: "Masters", field: "Computer Science", duration: "1 year", tuitionFee: 28250 },
    ],
  },
  // ─── United States ──────────────────────────────────────
  {
    name: "Northeastern University",
    country: "United States",
    city: "Boston",
    type: "Private",
    established: 1898,
    ranking: 375,
    websiteUrl: "https://www.northeastern.edu",
    coverImageUrl: "https://images.unsplash.com/photo-1576495199011-eb94736d05d6?w=800&auto=format&fit=crop",
    description: "Northeastern University is a private research university in Boston, known for its cooperative education program that integrates classroom study with professional experience.",
    intakes: ["September", "January", "May"],
    minIelts: 6.5,
    minToefl: 92,
    minGpa: 3.0,
    tuitionRangeMin: 28000,
    tuitionRangeMax: 58000,
    applicationFee: 75,
    studentCount: 38000,
    acceptanceRate: 0.20,
    programs: [
      { name: "MS in Computer Science", level: "Masters", field: "Computer Science", duration: "2 years", tuitionFee: 29500 },
      { name: "MS in Data Science", level: "Masters", field: "Computer Science", duration: "1.5 years", tuitionFee: 29500 },
      { name: "MS in Information Systems", level: "Masters", field: "Computer Science", duration: "2 years", tuitionFee: 29500 },
      { name: "BS in Computer Science", level: "Bachelors", field: "Computer Science", duration: "4 years", tuitionFee: 57592 },
    ],
  },
  {
    name: "Arizona State University",
    country: "United States",
    city: "Tempe",
    type: "Public",
    established: 1885,
    ranking: 179,
    websiteUrl: "https://www.asu.edu",
    coverImageUrl: "https://images.unsplash.com/photo-1580537659466-0a9bfa916a54?w=800&auto=format&fit=crop",
    description: "Arizona State University is a public research university in the Phoenix metropolitan area. It is one of the largest public universities by enrollment in the United States.",
    intakes: ["August", "January"],
    minIelts: 6.0,
    minToefl: 61,
    minGpa: 2.5,
    tuitionRangeMin: 18000,
    tuitionRangeMax: 32000,
    applicationFee: 70,
    studentCount: 140000,
    acceptanceRate: 0.88,
    programs: [
      { name: "MS in Computer Science", level: "Masters", field: "Computer Science", duration: "2 years", tuitionFee: 32000 },
      { name: "BS in Computer Science", level: "Bachelors", field: "Computer Science", duration: "4 years", tuitionFee: 31200 },
      { name: "Master of Business Administration", level: "Masters", field: "Business", duration: "2 years", tuitionFee: 28000 },
      { name: "BS in Nursing", level: "Bachelors", field: "Health Sciences", duration: "4 years", tuitionFee: 31200 },
    ],
  },
  // ─── New Zealand ────────────────────────────────────────
  {
    name: "University of Auckland",
    country: "New Zealand",
    city: "Auckland",
    type: "Public",
    established: 1883,
    ranking: 68,
    websiteUrl: "https://www.auckland.ac.nz",
    coverImageUrl: "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=800&auto=format&fit=crop",
    description: "The University of Auckland is the largest university in New Zealand. It is ranked as the top university in New Zealand and consistently among the top 100 globally.",
    intakes: ["February", "July"],
    minIelts: 6.0,
    minToefl: 80,
    minGpa: 2.8,
    tuitionRangeMin: 25000,
    tuitionRangeMax: 42000,
    applicationFee: 0,
    studentCount: 46000,
    acceptanceRate: 0.64,
    programs: [
      { name: "Master of Information Technology", level: "Masters", field: "Computer Science", duration: "1.5 years", tuitionFee: 39584 },
      { name: "Bachelor of Science (Computer Science)", level: "Bachelors", field: "Computer Science", duration: "3 years", tuitionFee: 37900 },
      { name: "Master of Business Administration", level: "Masters", field: "Business", duration: "15 months", tuitionFee: 67116 },
      { name: "Bachelor of Engineering (Honours)", level: "Bachelors", field: "Engineering", duration: "4 years", tuitionFee: 45110 },
    ],
  },
  {
    name: "University of Canterbury",
    country: "New Zealand",
    city: "Christchurch",
    type: "Public",
    established: 1873,
    ranking: 256,
    websiteUrl: "https://www.canterbury.ac.nz",
    coverImageUrl: "https://images.unsplash.com/photo-1594312915251-48db9280c8f0?w=800&auto=format&fit=crop",
    description: "The University of Canterbury is a university located in Christchurch, New Zealand. Known for engineering and science, it attracts students from over 80 countries.",
    intakes: ["February", "July"],
    minIelts: 6.0,
    minToefl: 80,
    minGpa: 2.5,
    tuitionRangeMin: 22000,
    tuitionRangeMax: 38000,
    applicationFee: 0,
    studentCount: 15000,
    acceptanceRate: 0.80,
    programs: [
      { name: "Master of Applied Data Science", level: "Masters", field: "Computer Science", duration: "1 year", tuitionFee: 34600 },
      { name: "Bachelor of Engineering (Honours)", level: "Bachelors", field: "Engineering", duration: "4 years", tuitionFee: 45000 },
      { name: "Master of Business Administration", level: "Masters", field: "Business", duration: "1 year", tuitionFee: 32000 },
    ],
  },
  // ─── Germany ────────────────────────────────────────────
  {
    name: "Technical University of Munich",
    country: "Germany",
    city: "Munich",
    type: "Public",
    established: 1868,
    ranking: 28,
    websiteUrl: "https://www.tum.de",
    coverImageUrl: "https://images.unsplash.com/photo-1560969184-10fe8719e047?w=800&auto=format&fit=crop",
    description: "The Technical University of Munich is a public research university in Munich. It is one of the highest-ranked universities in Germany and Europe, known for engineering and natural sciences.",
    intakes: ["October", "April"],
    minIelts: 6.5,
    minToefl: 88,
    minGpa: 3.0,
    tuitionRangeMin: 250,
    tuitionRangeMax: 750,
    applicationFee: 0,
    studentCount: 50000,
    acceptanceRate: 0.08,
    programs: [
      { name: "M.Sc. Informatics", level: "Masters", field: "Computer Science", duration: "2 years", tuitionFee: 286 },
      { name: "M.Sc. Data Engineering and Analytics", level: "Masters", field: "Computer Science", duration: "2 years", tuitionFee: 286 },
      { name: "B.Sc. Mechanical Engineering", level: "Bachelors", field: "Engineering", duration: "3 years", tuitionFee: 286 },
      { name: "M.Sc. Management & Technology", level: "Masters", field: "Business", duration: "2 years", tuitionFee: 286 },
    ],
  },
  // ─── Japan ──────────────────────────────────────────────
  {
    name: "University of Tokyo",
    country: "Japan",
    city: "Tokyo",
    type: "Public",
    established: 1877,
    ranking: 32,
    websiteUrl: "https://www.u-tokyo.ac.jp/en/",
    coverImageUrl: "https://images.unsplash.com/photo-1513407030348-c983a97b98d8?w=800&auto=format&fit=crop",
    description: "The University of Tokyo is a public research university in Tokyo. It is the top-ranked university in Japan and one of the most prestigious universities in Asia.",
    intakes: ["April", "October"],
    minIelts: 6.5,
    minToefl: 90,
    minGpa: 3.2,
    tuitionRangeMin: 3500,
    tuitionRangeMax: 6000,
    applicationFee: 0,
    studentCount: 28000,
    acceptanceRate: 0.30,
    programs: [
      { name: "Master of Information Science and Technology", level: "Masters", field: "Computer Science", duration: "2 years", tuitionFee: 5352 },
      { name: "Master of Engineering", level: "Masters", field: "Engineering", duration: "2 years", tuitionFee: 5352 },
      { name: "Master of Economics", level: "Masters", field: "Business", duration: "2 years", tuitionFee: 5352 },
    ],
  },
  // ─── South Korea ────────────────────────────────────────
  {
    name: "Seoul National University",
    country: "South Korea",
    city: "Seoul",
    type: "Public",
    established: 1946,
    ranking: 31,
    websiteUrl: "https://en.snu.ac.kr",
    coverImageUrl: "https://images.unsplash.com/photo-1517154421773-0529f29ea451?w=800&auto=format&fit=crop",
    description: "Seoul National University is a national research university in Seoul, South Korea. It is considered the most prestigious university in South Korea.",
    intakes: ["March", "September"],
    minIelts: 6.0,
    minToefl: 80,
    minGpa: 3.0,
    tuitionRangeMin: 4000,
    tuitionRangeMax: 8000,
    applicationFee: 60,
    studentCount: 28000,
    acceptanceRate: 0.24,
    programs: [
      { name: "MS in Computer Science and Engineering", level: "Masters", field: "Computer Science", duration: "2 years", tuitionFee: 6400 },
      { name: "MS in Data Science", level: "Masters", field: "Computer Science", duration: "2 years", tuitionFee: 6400 },
      { name: "MBA (Global)", level: "Masters", field: "Business", duration: "2 years", tuitionFee: 8500 },
    ],
  },
];
