export const universities = [
  // ── Australia ───────────────────────────────────────────────────────────────
  {
    name: "University of Melbourne",
    slug: "university-of-melbourne",
    country: "Australia", city: "Melbourne", state: "Victoria",
    type: "Public", ranking: 33, established: 1853,
    description: "Australia's leading research university, ranked in the top 50 globally.",
    website: "https://www.unimelb.edu.au",
    coverImageUrl: "https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=800&q=80",
    logoUrl: null, intakes: ["February", "July"], isActive: true,
    tuitionRangeMin: 35000, tuitionRangeMax: 50000, currency: "AUD",
    programs: [
      { name: "Master of Information Technology", level: "Masters", field: "Computer Science", durationMonths: 24, tuitionFee: 43008, currency: "AUD", intakes: ["February", "July"] },
      { name: "Master of Business Administration", level: "Masters", field: "Business", durationMonths: 24, tuitionFee: 47000, currency: "AUD", intakes: ["February", "July"] },
      { name: "Bachelor of Science", level: "Bachelors", field: "Science", durationMonths: 36, tuitionFee: 38000, currency: "AUD", intakes: ["February"] },
      { name: "Master of Data Science", level: "Masters", field: "Data Science", durationMonths: 24, tuitionFee: 44000, currency: "AUD", intakes: ["February", "July"] },
      { name: "Master of Engineering", level: "Masters", field: "Engineering", durationMonths: 24, tuitionFee: 45000, currency: "AUD", intakes: ["February", "July"] },
    ],
  },
  {
    name: "Monash University",
    slug: "monash-university",
    country: "Australia", city: "Melbourne", state: "Victoria",
    type: "Public", ranking: 57, established: 1958,
    description: "A leading Australian university with a global presence.",
    website: "https://www.monash.edu",
    coverImageUrl: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&q=80",
    logoUrl: null, intakes: ["February", "July"], isActive: true,
    tuitionRangeMin: 32000, tuitionRangeMax: 48000, currency: "AUD",
    programs: [
      { name: "Master of Information Technology", level: "Masters", field: "Computer Science", durationMonths: 24, tuitionFee: 40800, currency: "AUD", intakes: ["February", "July"] },
      { name: "Bachelor of Engineering (Hons)", level: "Bachelors", field: "Engineering", durationMonths: 48, tuitionFee: 40000, currency: "AUD", intakes: ["February"] },
      { name: "Master of Business Analytics", level: "Masters", field: "Data Science", durationMonths: 18, tuitionFee: 38000, currency: "AUD", intakes: ["February", "July"] },
      { name: "Bachelor of Nursing", level: "Bachelors", field: "Nursing", durationMonths: 36, tuitionFee: 33000, currency: "AUD", intakes: ["February"] },
    ],
  },
  {
    name: "University of Sydney",
    slug: "university-of-sydney",
    country: "Australia", city: "Sydney", state: "New South Wales",
    type: "Public", ranking: 41, established: 1850,
    description: "Australia's first university and one of its finest.",
    website: "https://www.sydney.edu.au",
    coverImageUrl: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&q=80",
    logoUrl: null, intakes: ["February", "August"], isActive: true,
    tuitionRangeMin: 36000, tuitionRangeMax: 52000, currency: "AUD",
    programs: [
      { name: "Master of Professional Engineering", level: "Masters", field: "Engineering", durationMonths: 24, tuitionFee: 47000, currency: "AUD", intakes: ["February", "August"] },
      { name: "Master of Commerce", level: "Masters", field: "Business", durationMonths: 18, tuitionFee: 42000, currency: "AUD", intakes: ["February", "August"] },
      { name: "Bachelor of Advanced Computing", level: "Bachelors", field: "Computer Science", durationMonths: 36, tuitionFee: 44000, currency: "AUD", intakes: ["February"] },
    ],
  },
  {
    name: "RMIT University",
    slug: "rmit-university",
    country: "Australia", city: "Melbourne", state: "Victoria",
    type: "Public", ranking: 140, established: 1887,
    description: "A global university of technology, design and enterprise.",
    website: "https://www.rmit.edu.au",
    coverImageUrl: "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    logoUrl: null, intakes: ["February", "July"], isActive: true,
    tuitionRangeMin: 28000, tuitionRangeMax: 40000, currency: "AUD",
    programs: [
      { name: "Bachelor of Information Technology", level: "Bachelors", field: "Computer Science", durationMonths: 36, tuitionFee: 31000, currency: "AUD", intakes: ["February", "July"] },
      { name: "Master of Cyber Security", level: "Masters", field: "Computer Science", durationMonths: 24, tuitionFee: 35000, currency: "AUD", intakes: ["February", "July"] },
      { name: "Bachelor of Business", level: "Bachelors", field: "Business", durationMonths: 36, tuitionFee: 30000, currency: "AUD", intakes: ["February", "July"] },
    ],
  },
  // ── Canada ──────────────────────────────────────────────────────────────────
  {
    name: "University of Toronto",
    slug: "university-of-toronto",
    country: "Canada", city: "Toronto", state: "Ontario",
    type: "Public", ranking: 21, established: 1827,
    description: "Canada's top university and a world leader in research.",
    website: "https://www.utoronto.ca",
    coverImageUrl: "https://images.unsplash.com/photo-1569447891824-5e604cbfa893?w=800&q=80",
    logoUrl: null, intakes: ["September"], isActive: true,
    tuitionRangeMin: 30000, tuitionRangeMax: 60000, currency: "CAD",
    programs: [
      { name: "Master of Engineering (MEng)", level: "Masters", field: "Engineering", durationMonths: 12, tuitionFee: 28000, currency: "CAD", intakes: ["September"] },
      { name: "Master of Science in Applied Computing", level: "Masters", field: "Computer Science", durationMonths: 16, tuitionFee: 26000, currency: "CAD", intakes: ["September"] },
      { name: "Bachelor of Computer Science", level: "Bachelors", field: "Computer Science", durationMonths: 48, tuitionFee: 50000, currency: "CAD", intakes: ["September"] },
      { name: "Master of Business Administration", level: "Masters", field: "Business", durationMonths: 24, tuitionFee: 55000, currency: "CAD", intakes: ["September"] },
    ],
  },
  {
    name: "University of British Columbia",
    slug: "university-of-british-columbia",
    country: "Canada", city: "Vancouver", state: "British Columbia",
    type: "Public", ranking: 38, established: 1908,
    description: "A global centre for teaching, learning and research, situated on the Pacific coast.",
    website: "https://www.ubc.ca",
    coverImageUrl: "https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?w=800&q=80",
    logoUrl: null, intakes: ["September", "January"], isActive: true,
    tuitionRangeMin: 28000, tuitionRangeMax: 50000, currency: "CAD",
    programs: [
      { name: "Master of Data Science", level: "Masters", field: "Data Science", durationMonths: 10, tuitionFee: 24000, currency: "CAD", intakes: ["September"] },
      { name: "Bachelor of Applied Science (Engineering)", level: "Bachelors", field: "Engineering", durationMonths: 48, tuitionFee: 44000, currency: "CAD", intakes: ["September"] },
      { name: "Master of Business Administration", level: "Masters", field: "Business", durationMonths: 20, tuitionFee: 48000, currency: "CAD", intakes: ["September"] },
    ],
  },
  {
    name: "University of Waterloo",
    slug: "university-of-waterloo",
    country: "Canada", city: "Waterloo", state: "Ontario",
    type: "Public", ranking: 173, established: 1957,
    description: "Canada's top innovation university, famous for co-op education and tech programs.",
    website: "https://uwaterloo.ca",
    coverImageUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&q=80",
    logoUrl: null, intakes: ["September", "January"], isActive: true,
    tuitionRangeMin: 25000, tuitionRangeMax: 45000, currency: "CAD",
    programs: [
      { name: "Master of Mathematics in Computer Science", level: "Masters", field: "Computer Science", durationMonths: 24, tuitionFee: 18000, currency: "CAD", intakes: ["September", "January"] },
      { name: "Bachelor of Software Engineering", level: "Bachelors", field: "Engineering", durationMonths: 48, tuitionFee: 38000, currency: "CAD", intakes: ["September", "January"] },
      { name: "Master of Business, Entrepreneurship & Technology", level: "Masters", field: "Business", durationMonths: 16, tuitionFee: 35000, currency: "CAD", intakes: ["September"] },
    ],
  },
  // ── USA ─────────────────────────────────────────────────────────────────────
  {
    name: "Northeastern University",
    slug: "northeastern-university",
    country: "USA", city: "Boston", state: "Massachusetts",
    type: "Private", ranking: 185, established: 1898,
    description: "A global research university known for experiential learning and co-op programs.",
    website: "https://www.northeastern.edu",
    coverImageUrl: "https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=800&q=80",
    logoUrl: null, intakes: ["September", "January"], isActive: true,
    tuitionRangeMin: 50000, tuitionRangeMax: 65000, currency: "USD",
    programs: [
      { name: "Master of Science in Computer Science", level: "Masters", field: "Computer Science", durationMonths: 18, tuitionFee: 29000, currency: "USD", intakes: ["September", "January"] },
      { name: "Master of Science in Data Science", level: "Masters", field: "Data Science", durationMonths: 18, tuitionFee: 28000, currency: "USD", intakes: ["September", "January"] },
      { name: "Master of Science in Information Systems", level: "Masters", field: "Computer Science", durationMonths: 18, tuitionFee: 27000, currency: "USD", intakes: ["September", "January"] },
    ],
  },
  {
    name: "Arizona State University",
    slug: "arizona-state-university",
    country: "USA", city: "Tempe", state: "Arizona",
    type: "Public", ranking: 216, established: 1885,
    description: "America's most innovative university for five consecutive years.",
    website: "https://www.asu.edu",
    coverImageUrl: "https://images.unsplash.com/photo-1571260899304-425eee4c7efc?w=800&q=80",
    logoUrl: null, intakes: ["August", "January"], isActive: true,
    tuitionRangeMin: 28000, tuitionRangeMax: 45000, currency: "USD",
    programs: [
      { name: "Master of Science in Computer Science", level: "Masters", field: "Computer Science", durationMonths: 18, tuitionFee: 28000, currency: "USD", intakes: ["August", "January"] },
      { name: "Master of Business Administration", level: "Masters", field: "Business", durationMonths: 20, tuitionFee: 30000, currency: "USD", intakes: ["August"] },
      { name: "Bachelor of Science in Engineering", level: "Bachelors", field: "Engineering", durationMonths: 48, tuitionFee: 32000, currency: "USD", intakes: ["August", "January"] },
    ],
  },
  // ── UK ──────────────────────────────────────────────────────────────────────
  {
    name: "University of Manchester",
    slug: "university-of-manchester",
    country: "UK", city: "Manchester", state: "England",
    type: "Public", ranking: 32, established: 1824,
    description: "A world-class research university in the heart of England.",
    website: "https://www.manchester.ac.uk",
    coverImageUrl: "https://images.unsplash.com/photo-1591123120675-6f7f1aae0e3b?w=800&q=80",
    logoUrl: null, intakes: ["September"], isActive: true,
    tuitionRangeMin: 20000, tuitionRangeMax: 35000, currency: "GBP",
    programs: [
      { name: "MSc Computer Science", level: "Masters", field: "Computer Science", durationMonths: 12, tuitionFee: 26000, currency: "GBP", intakes: ["September"] },
      { name: "MSc Data Science", level: "Masters", field: "Data Science", durationMonths: 12, tuitionFee: 25000, currency: "GBP", intakes: ["September"] },
      { name: "MBA", level: "Masters", field: "Business", durationMonths: 12, tuitionFee: 35000, currency: "GBP", intakes: ["September"] },
    ],
  },
  {
    name: "University of Leeds",
    slug: "university-of-leeds",
    country: "UK", city: "Leeds", state: "England",
    type: "Public", ranking: 92, established: 1904,
    description: "A Russell Group university known for research and student experience.",
    website: "https://www.leeds.ac.uk",
    coverImageUrl: "https://images.unsplash.com/photo-1543269865-cbf427effbad?w=800&q=80",
    logoUrl: null, intakes: ["September"], isActive: true,
    tuitionRangeMin: 18000, tuitionRangeMax: 28000, currency: "GBP",
    programs: [
      { name: "MSc Artificial Intelligence", level: "Masters", field: "Computer Science", durationMonths: 12, tuitionFee: 25000, currency: "GBP", intakes: ["September"] },
      { name: "MSc Finance", level: "Masters", field: "Business", durationMonths: 12, tuitionFee: 22000, currency: "GBP", intakes: ["September"] },
      { name: "BEng Mechanical Engineering", level: "Bachelors", field: "Engineering", durationMonths: 36, tuitionFee: 22000, currency: "GBP", intakes: ["September"] },
    ],
  },
  // ── New Zealand ──────────────────────────────────────────────────────────────
  {
    name: "University of Auckland",
    slug: "university-of-auckland",
    country: "New Zealand", city: "Auckland", state: "Auckland",
    type: "Public", ranking: 68, established: 1883,
    description: "New Zealand's leading research university.",
    website: "https://www.auckland.ac.nz",
    coverImageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    logoUrl: null, intakes: ["February", "July"], isActive: true,
    tuitionRangeMin: 28000, tuitionRangeMax: 42000, currency: "NZD",
    programs: [
      { name: "Master of Information Technology", level: "Masters", field: "Computer Science", durationMonths: 18, tuitionFee: 34000, currency: "NZD", intakes: ["February", "July"] },
      { name: "Bachelor of Engineering (Hons)", level: "Bachelors", field: "Engineering", durationMonths: 48, tuitionFee: 36000, currency: "NZD", intakes: ["February"] },
      { name: "Master of Business Administration", level: "Masters", field: "Business", durationMonths: 12, tuitionFee: 38000, currency: "NZD", intakes: ["February"] },
    ],
  },
];

export const studyFields = [
  { name: "Computer Science", slug: "computer-science", description: "Programming, software engineering, AI, and more", displayOrder: 1 },
  { name: "Business & Management", slug: "business-management", description: "MBA, finance, marketing, and entrepreneurship", displayOrder: 2 },
  { name: "Engineering", slug: "engineering", description: "Mechanical, civil, electrical, and more", displayOrder: 3 },
  { name: "Data Science", slug: "data-science", description: "Analytics, machine learning, and big data", displayOrder: 4 },
  { name: "Nursing & Healthcare", slug: "nursing-healthcare", description: "Nursing, medicine, and allied health sciences", displayOrder: 5 },
  { name: "Architecture & Design", slug: "architecture-design", description: "Architecture, interior design, and urban planning", displayOrder: 6 },
  { name: "Arts & Humanities", slug: "arts-humanities", description: "Literature, history, philosophy, and fine arts", displayOrder: 7 },
  { name: "Law", slug: "law", description: "LLB, LLM, and legal studies", displayOrder: 8 },
];

export const countryGuides = [
  {
    country: "Australia", slug: "australia", flagEmoji: "🇦🇺",
    bannerImageUrl: "https://images.unsplash.com/photo-1523482580672-f109ba8cb9be?w=1200&q=80",
    overview: "Australia is one of the most popular destinations for international students, offering world-class education, a multicultural society, and excellent post-study work opportunities.",
    whyStudyHere: ["Top-ranked universities", "Post-study work visa (2-4 years)", "Multicultural & welcoming", "High quality of life", "Strong job market"],
    livingCost: { min: 1500, max: 2500, currency: "AUD", period: "monthly" },
    visaRequirements: { type: "Student Visa (Subclass 500)", processingTime: "4-6 weeks", englishRequired: true, minIELTS: 6.0 },
    intakes: ["February", "July"],
    currency: "AUD", avgTuitionMin: 28000, avgTuitionMax: 50000, universityCount: 43, isActive: true, displayOrder: 1,
  },
  {
    country: "Canada", slug: "canada", flagEmoji: "🇨🇦",
    bannerImageUrl: "https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=1200&q=80",
    overview: "Canada offers excellent education, a safe environment, and a clear pathway to permanent residency, making it a top choice for Nepali students.",
    whyStudyHere: ["PR pathway after graduation", "Affordable tuition vs USA", "Safe and multicultural", "Work while studying (20hrs/week)", "PGWP up to 3 years"],
    livingCost: { min: 1200, max: 2000, currency: "CAD", period: "monthly" },
    visaRequirements: { type: "Study Permit", processingTime: "4-16 weeks", englishRequired: true, minIELTS: 6.0 },
    intakes: ["September", "January"],
    currency: "CAD", avgTuitionMin: 20000, avgTuitionMax: 45000, universityCount: 96, isActive: true, displayOrder: 2,
  },
  {
    country: "UK", slug: "uk", flagEmoji: "🇬🇧",
    bannerImageUrl: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=1200&q=80",
    overview: "The UK is home to some of the world's oldest and most prestigious universities, with shorter degree durations saving both time and money.",
    whyStudyHere: ["Prestigious institutions (Oxford, Cambridge)", "1-year Master's programs", "Graduate Route Visa (2 years)", "Rich cultural history", "Strong research ecosystem"],
    livingCost: { min: 1200, max: 2000, currency: "GBP", period: "monthly" },
    visaRequirements: { type: "Student Visa", processingTime: "3 weeks", englishRequired: true, minIELTS: 6.0 },
    intakes: ["September"],
    currency: "GBP", avgTuitionMin: 15000, avgTuitionMax: 35000, universityCount: 160, isActive: true, displayOrder: 3,
  },
  {
    country: "New Zealand", slug: "new-zealand", flagEmoji: "🇳🇿",
    bannerImageUrl: "https://images.unsplash.com/photo-1469521669194-babb45599def?w=1200&q=80",
    overview: "New Zealand offers breathtaking natural beauty, a safe environment, and a high quality of life alongside excellent academic institutions.",
    whyStudyHere: ["Safe and peaceful environment", "Post-study work rights", "Beautiful natural landscapes", "Small class sizes", "English-speaking country"],
    livingCost: { min: 1200, max: 1800, currency: "NZD", period: "monthly" },
    visaRequirements: { type: "Student Visa", processingTime: "4-6 weeks", englishRequired: true, minIELTS: 6.0 },
    intakes: ["February", "July"],
    currency: "NZD", avgTuitionMin: 22000, avgTuitionMax: 38000, universityCount: 8, isActive: true, displayOrder: 4,
  },
  {
    country: "USA", slug: "usa", flagEmoji: "🇺🇸",
    bannerImageUrl: "https://images.unsplash.com/photo-1485738422979-f5c462d49f74?w=1200&q=80",
    overview: "The United States has the world's largest number of top-ranked universities and offers unparalleled research and career opportunities.",
    whyStudyHere: ["World's top-ranked universities", "Optional Practical Training (OPT)", "Vast research funding", "Diverse program options", "Strong alumni networks"],
    livingCost: { min: 1500, max: 3000, currency: "USD", period: "monthly" },
    visaRequirements: { type: "F-1 Student Visa", processingTime: "4-8 weeks", englishRequired: true, minIELTS: 6.5 },
    intakes: ["August/September", "January"],
    currency: "USD", avgTuitionMin: 20000, avgTuitionMax: 65000, universityCount: 4000, isActive: true, displayOrder: 5,
  },
];

export const helpArticles = [
  { category: "getting-started", title: "How to create your Unifinders profile", slug: "create-profile", content: "Step-by-step guide to setting up your profile to get personalized university recommendations.", tags: ["profile", "onboarding"], displayOrder: 1 },
  { category: "getting-started", title: "How to search for universities", slug: "search-universities", content: "Learn how to use filters to find universities that match your academic background and preferences.", tags: ["search", "universities"], displayOrder: 2 },
  { category: "applications", title: "How to track your application status", slug: "track-application", content: "Your counselor will update your application status at each stage. Here's what each status means.", tags: ["applications", "status"], displayOrder: 1 },
  { category: "applications", title: "What documents do I need to apply?", slug: "required-documents", content: "Most universities require academic transcripts, English test scores, a statement of purpose, and a CV.", tags: ["documents", "applications"], displayOrder: 2 },
  { category: "visa", title: "Student visa requirements for Australia", slug: "australia-visa", content: "To get an Australian student visa (Subclass 500), you need a Confirmation of Enrolment (CoE) and OSHC health insurance.", tags: ["visa", "australia"], displayOrder: 1 },
  { category: "visa", title: "Canada study permit explained", slug: "canada-study-permit", content: "A study permit is required for programs longer than 6 months. Apply as early as possible as processing can take 4-16 weeks.", tags: ["visa", "canada"], displayOrder: 2 },
  { category: "scholarships", title: "Top scholarships for Nepali students", slug: "scholarships-nepal", content: "Discover scholarships like Aga Khan, Chevening, Australia Awards, and university-specific grants for Nepali students.", tags: ["scholarships", "funding"], displayOrder: 1 },
  { category: "scholarships", title: "How to write a scholarship essay", slug: "scholarship-essay", content: "Tips and templates for writing a compelling scholarship essay that highlights your achievements and goals.", tags: ["scholarships", "essay"], displayOrder: 2 },
];
